&lt;Project Sdk="Microsoft.NET.Sdk.Web"&gt;
  &lt;PropertyGroup&gt;
    &lt;TargetFramework&gt;net8.0&lt;/TargetFramework&gt;
    &lt;Nullable&gt;enable&lt;/Nullable&gt;
    &lt;ImplicitUsings&gt;enable&lt;/ImplicitUsings&gt;
  &lt;/PropertyGroup&gt;

  &lt;ItemGroup&gt;
    &lt;!-- Core Dependencies --&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" /&gt;
    &lt;PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" /&gt;
    &lt;PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" /&gt;
    
    &lt;!-- Authentication --&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" /&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="8.0.0" /&gt;
    &lt;PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" /&gt;
    
    &lt;!-- AutoMapper --&gt;
    &lt;PackageReference Include="AutoMapper.Collection" Version="9.0.0" /&gt;
    &lt;PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" /&gt;
    
    &lt;!-- Modern UI Libraries --&gt;
    &lt;PackageReference Include="Bootstrap" Version="5.3.2" /&gt;
    &lt;PackageReference Include="jQuery" Version="3.7.1" /&gt;
    &lt;PackageReference Include="jQuery.Validation" Version="1.19.5" /&gt;
    &lt;PackageReference Include="toastr" Version="2.1.1" /&gt;
    
    &lt;!-- Application Insights --&gt;
    &lt;PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" /&gt;
  &lt;/ItemGroup&gt;
&lt;/Project&gt;